### ISSUE TITLE
demo page not loading.. lots of error in console.

### ISSUE THREAD

**Issue by ghhv** [excubo-ag/Blazor.Grids#28]
fyi
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://excubo-ag.github.io/Blazor.Grids/_framework/Microsoft.Extensions.Configuration.Json.wasm' with computed SHA-256 integrity 'Sxmy2ZS134URxbHEvdbS6NcQ3zXS7UWx/5ZPpwiW7FA='. The resource has been blocked.Understand this error
Blazor.Grids/:1 Unknown error occurred while trying to verify integrity.Understand this error
blazor.webassembly.js:1 Error in mono_download_assets: Error: download 'https://excubo-ag.github.io/Blazor.Grids/_framework/Microsoft.Extensions.Configuration.Json.wasm' for Microsoft.Extensions.Configuration.Json.wasm failed 0 TypeError: Failed to fetch
Dt @ blazor.webassembly.js:1
(anonymous) @ dotnet.js:3
Promise.catch (async)
Z @ dotnet.js:3
await in Z (async)
(anonymous) @ dotnet.js:3
setTimeout (async)
(anonymous) @ dotnet.js:3
await in (anonymous) (async)
Pe @ dotnet.js:3
await in Pe (async)
create @ dotnet.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
load @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
hn @ blazor.webassembly.js:1
mn @ blazor.webassembly.js:1
fn @ blazor.webassembly.js:1
An @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1Understand this error
Blazor.Grids/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://excubo-ag.github.io/Blazor.Grids/_framework/Microsoft.Extensions.DependencyInjection.wasm' with computed SHA-256 integrity 'gg8xZqJsBBrrNEyUGzYqhL3sqkuZ4AHAvdTdL9nZ0S0='. The resource has been blocked.Understand this error
Blazor.Grids/:1 Unknown error occurred while trying to verify integrity.Understand this error
dotnet.js:3 Uncaught (in promise) TypeError: Failed to fetch
    at Object.A [as fetch_like] (dotnet.js:3:4508)
    at dotnet.js:3:11593
    at dotnet.js:3:11609
```

**Comment by stefanloerwald** [comment]
Thanks for raising this issue, @ghhv. This was caused by some issues in the deployment process and this is now resolved.

**Comment by ghhv** [comment]
👍👍
